# Generated by Django 5.1.3 on 2024-12-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ("created_at",),
                "permissions": [
                    ("can_view_all_mailing", "Can view all mailing"),
                    ("can_disable_mailing", "Can disable mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
