# Generated by Django 5.1.3 on 2024-12-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_attempt_owner_client_owner_mailing_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attempt",
            old_name="owner",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="owner",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="owner",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="owner",
            new_name="user",
        ),
    ]
