# Generated by Django 5.1.3 on 2024-12-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="Post",
        ),
    ]
